[project]
name = "mcp-demo"
version = "0.1.0"
description = "A Virtual Environment that contains packages regarding MCP (server and client), it contains langchain tools in specific along with FastMCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.14.1",
    "langchain>=1.3.14",
    "langchain-core>=1.5.3",
    "langchain-groq>=1.1.3",
    "langchain-mcp-adapters>=0.1.3",
    "langgraph>=1.2.10",
    "mcp>=1.24.0,<2.0",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
]
